// @generated by tools/generate_eobi_schema.py; do not edit by hand.
// Source: Deutsche Boerse T7 EOBI XML representation.
// Input: eobi.xml

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum FieldType {
    I8,
    U8,
    I16Le,
    U16Le,
    I32Le,
    U32Le,
    I64Le,
    U64Le,
    Decimal64Le,
    FixedBytes(usize),
}

impl FieldType {
    pub const fn width(self) -> usize {
        match self {
            Self::I8 | Self::U8 => 1,
            Self::I16Le | Self::U16Le => 2,
            Self::I32Le | Self::U32Le => 4,
            Self::I64Le | Self::U64Le | Self::Decimal64Le => 8,
            Self::FixedBytes(width) => width,
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct FieldDesc {
    pub name: &'static str,
    pub offset: usize,
    pub ty: FieldType,
}

impl FieldDesc {
    pub const fn end_offset(self) -> usize {
        self.offset + self.ty.width()
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum EventTemplate {
    Unsupported,
    Heartbeat,
    PacketHeader,
    ProductStateChange,
    InstrumentStateChange,
    InstrumentSummary,
    ProductSummary,
    OrderAdd,
    OrderModify,
    OrderModifySamePrio,
    OrderDelete,
    OrderMassDelete,
    PartialOrderExecution,
    FullOrderExecution,
    SnapshotOrder,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct MessageDesc {
    pub template_id: u16,
    pub name: &'static str,
    pub min_block_len: usize,
    pub event_template: EventTemplate,
    pub fields: &'static [FieldDesc],
}

impl MessageDesc {
    pub fn validate(self) -> Result<(), &'static str> {
        for field in self.fields {
            if field.end_offset() > self.min_block_len {
                return Err(field.name);
            }
        }
        Ok(())
    }
}

pub const EOBI_INTERFACE_VERSION: &str = "14.1";
pub const EOBI_BUILD_NUMBER: &str = "141.420.0.ga-141004040-68";
pub const EOBI_MESSAGE_HEADER_LEN: usize = 8;

pub const HEARTBEAT_FIELDS: &[FieldDesc] = &[
    FieldDesc {
        name: "BodyLen",
        offset: 0,
        ty: FieldType::U16Le,
    },
    FieldDesc {
        name: "TemplateID",
        offset: 2,
        ty: FieldType::U16Le,
    },
    FieldDesc {
        name: "MsgSeqNum",
        offset: 4,
        ty: FieldType::U32Le,
    },
    FieldDesc {
        name: "LastMsgSeqNumProcessed",
        offset: 8,
        ty: FieldType::U32Le,
    },
    FieldDesc {
        name: "Pad4",
        offset: 12,
        ty: FieldType::FixedBytes(4),
    },
];

pub mod heartbeat {
    pub const TEMPLATE_ID: u16 = 13001;
    pub const MIN_BLOCK_LEN: usize = 16;
    pub const BODY_LEN_OFFSET: usize = 0;
    pub const TEMPLATE_ID_OFFSET: usize = 2;
    pub const MSG_SEQ_NUM_OFFSET: usize = 4;
    pub const LAST_MSG_SEQ_NUM_PROCESSED_OFFSET: usize = 8;
    pub const PAD4_OFFSET: usize = 12;
}

pub const PACKETHEADER_FIELDS: &[FieldDesc] = &[
    FieldDesc {
        name: "BodyLen",
        offset: 0,
        ty: FieldType::U16Le,
    },
    FieldDesc {
        name: "TemplateID",
        offset: 2,
        ty: FieldType::U16Le,
    },
    FieldDesc {
        name: "MsgSeqNum",
        offset: 4,
        ty: FieldType::U32Le,
    },
    FieldDesc {
        name: "ApplSeqNum",
        offset: 8,
        ty: FieldType::U32Le,
    },
    FieldDesc {
        name: "MarketSegmentID",
        offset: 12,
        ty: FieldType::I32Le,
    },
    FieldDesc {
        name: "PartitionID",
        offset: 16,
        ty: FieldType::U8,
    },
    FieldDesc {
        name: "CompletionIndicator",
        offset: 17,
        ty: FieldType::U8,
    },
    FieldDesc {
        name: "ApplSeqResetIndicator",
        offset: 18,
        ty: FieldType::U8,
    },
    FieldDesc {
        name: "DSCP",
        offset: 19,
        ty: FieldType::U8,
    },
    FieldDesc {
        name: "Pad4",
        offset: 20,
        ty: FieldType::FixedBytes(4),
    },
    FieldDesc {
        name: "TransactTime",
        offset: 24,
        ty: FieldType::U64Le,
    },
];

pub mod packet_header {
    pub const TEMPLATE_ID: u16 = 13002;
    pub const MIN_BLOCK_LEN: usize = 32;
    pub const BODY_LEN_OFFSET: usize = 0;
    pub const TEMPLATE_ID_OFFSET: usize = 2;
    pub const MSG_SEQ_NUM_OFFSET: usize = 4;
    pub const APPL_SEQ_NUM_OFFSET: usize = 8;
    pub const MARKET_SEGMENT_ID_OFFSET: usize = 12;
    pub const PARTITION_ID_OFFSET: usize = 16;
    pub const COMPLETION_INDICATOR_OFFSET: usize = 17;
    pub const APPL_SEQ_RESET_INDICATOR_OFFSET: usize = 18;
    pub const DSCP_OFFSET: usize = 19;
    pub const PAD4_OFFSET: usize = 20;
    pub const TRANSACT_TIME_OFFSET: usize = 24;
}

pub const ORDERADD_FIELDS: &[FieldDesc] = &[
    FieldDesc {
        name: "BodyLen",
        offset: 0,
        ty: FieldType::U16Le,
    },
    FieldDesc {
        name: "TemplateID",
        offset: 2,
        ty: FieldType::U16Le,
    },
    FieldDesc {
        name: "MsgSeqNum",
        offset: 4,
        ty: FieldType::U32Le,
    },
    FieldDesc {
        name: "RequestTime",
        offset: 8,
        ty: FieldType::U64Le,
    },
    FieldDesc {
        name: "SecurityID",
        offset: 16,
        ty: FieldType::I64Le,
    },
    FieldDesc {
        name: "TrdRegTSTimePriority",
        offset: 24,
        ty: FieldType::U64Le,
    },
    FieldDesc {
        name: "DisplayQty",
        offset: 32,
        ty: FieldType::Decimal64Le,
    },
    FieldDesc {
        name: "Side",
        offset: 40,
        ty: FieldType::U8,
    },
    FieldDesc {
        name: "OrdType",
        offset: 41,
        ty: FieldType::U8,
    },
    FieldDesc {
        name: "HHIIndicator",
        offset: 42,
        ty: FieldType::I8,
    },
    FieldDesc {
        name: "Pad5",
        offset: 43,
        ty: FieldType::FixedBytes(5),
    },
    FieldDesc {
        name: "Price",
        offset: 48,
        ty: FieldType::Decimal64Le,
    },
];

pub mod order_add {
    pub const TEMPLATE_ID: u16 = 13100;
    pub const MIN_BLOCK_LEN: usize = 56;
    pub const BODY_LEN_OFFSET: usize = 0;
    pub const TEMPLATE_ID_OFFSET: usize = 2;
    pub const MSG_SEQ_NUM_OFFSET: usize = 4;
    pub const REQUEST_TIME_OFFSET: usize = 8;
    pub const SECURITY_ID_OFFSET: usize = 16;
    pub const TRD_REG_TSTIME_PRIORITY_OFFSET: usize = 24;
    pub const DISPLAY_QTY_OFFSET: usize = 32;
    pub const SIDE_OFFSET: usize = 40;
    pub const ORD_TYPE_OFFSET: usize = 41;
    pub const HHIINDICATOR_OFFSET: usize = 42;
    pub const PAD5_OFFSET: usize = 43;
    pub const PRICE_OFFSET: usize = 48;
}

pub const ORDERMODIFY_FIELDS: &[FieldDesc] = &[
    FieldDesc {
        name: "BodyLen",
        offset: 0,
        ty: FieldType::U16Le,
    },
    FieldDesc {
        name: "TemplateID",
        offset: 2,
        ty: FieldType::U16Le,
    },
    FieldDesc {
        name: "MsgSeqNum",
        offset: 4,
        ty: FieldType::U32Le,
    },
    FieldDesc {
        name: "RequestTime",
        offset: 8,
        ty: FieldType::U64Le,
    },
    FieldDesc {
        name: "TrdRegTSPrevTimePriority",
        offset: 16,
        ty: FieldType::U64Le,
    },
    FieldDesc {
        name: "PrevPrice",
        offset: 24,
        ty: FieldType::Decimal64Le,
    },
    FieldDesc {
        name: "PrevDisplayQty",
        offset: 32,
        ty: FieldType::Decimal64Le,
    },
    FieldDesc {
        name: "SecurityID",
        offset: 40,
        ty: FieldType::I64Le,
    },
    FieldDesc {
        name: "TrdRegTSTimePriority",
        offset: 48,
        ty: FieldType::U64Le,
    },
    FieldDesc {
        name: "DisplayQty",
        offset: 56,
        ty: FieldType::Decimal64Le,
    },
    FieldDesc {
        name: "Side",
        offset: 64,
        ty: FieldType::U8,
    },
    FieldDesc {
        name: "OrdType",
        offset: 65,
        ty: FieldType::U8,
    },
    FieldDesc {
        name: "HHIIndicator",
        offset: 66,
        ty: FieldType::I8,
    },
    FieldDesc {
        name: "Pad5",
        offset: 67,
        ty: FieldType::FixedBytes(5),
    },
    FieldDesc {
        name: "Price",
        offset: 72,
        ty: FieldType::Decimal64Le,
    },
    FieldDesc {
        name: "PrevPriceHHIIndicator",
        offset: 80,
        ty: FieldType::I8,
    },
    FieldDesc {
        name: "Pad7",
        offset: 81,
        ty: FieldType::FixedBytes(7),
    },
];

pub mod order_modify {
    pub const TEMPLATE_ID: u16 = 13101;
    pub const MIN_BLOCK_LEN: usize = 88;
    pub const BODY_LEN_OFFSET: usize = 0;
    pub const TEMPLATE_ID_OFFSET: usize = 2;
    pub const MSG_SEQ_NUM_OFFSET: usize = 4;
    pub const REQUEST_TIME_OFFSET: usize = 8;
    pub const TRD_REG_TSPREV_TIME_PRIORITY_OFFSET: usize = 16;
    pub const PREV_PRICE_OFFSET: usize = 24;
    pub const PREV_DISPLAY_QTY_OFFSET: usize = 32;
    pub const SECURITY_ID_OFFSET: usize = 40;
    pub const TRD_REG_TSTIME_PRIORITY_OFFSET: usize = 48;
    pub const DISPLAY_QTY_OFFSET: usize = 56;
    pub const SIDE_OFFSET: usize = 64;
    pub const ORD_TYPE_OFFSET: usize = 65;
    pub const HHIINDICATOR_OFFSET: usize = 66;
    pub const PAD5_OFFSET: usize = 67;
    pub const PRICE_OFFSET: usize = 72;
    pub const PREV_PRICE_HHIINDICATOR_OFFSET: usize = 80;
    pub const PAD7_OFFSET: usize = 81;
}

pub const ORDERDELETE_FIELDS: &[FieldDesc] = &[
    FieldDesc {
        name: "BodyLen",
        offset: 0,
        ty: FieldType::U16Le,
    },
    FieldDesc {
        name: "TemplateID",
        offset: 2,
        ty: FieldType::U16Le,
    },
    FieldDesc {
        name: "MsgSeqNum",
        offset: 4,
        ty: FieldType::U32Le,
    },
    FieldDesc {
        name: "RequestTime",
        offset: 8,
        ty: FieldType::U64Le,
    },
    FieldDesc {
        name: "TransactTime",
        offset: 16,
        ty: FieldType::U64Le,
    },
    FieldDesc {
        name: "SecurityID",
        offset: 24,
        ty: FieldType::I64Le,
    },
    FieldDesc {
        name: "TrdRegTSTimePriority",
        offset: 32,
        ty: FieldType::U64Le,
    },
    FieldDesc {
        name: "DisplayQty",
        offset: 40,
        ty: FieldType::Decimal64Le,
    },
    FieldDesc {
        name: "Side",
        offset: 48,
        ty: FieldType::U8,
    },
    FieldDesc {
        name: "OrdType",
        offset: 49,
        ty: FieldType::U8,
    },
    FieldDesc {
        name: "HHIIndicator",
        offset: 50,
        ty: FieldType::I8,
    },
    FieldDesc {
        name: "Pad5",
        offset: 51,
        ty: FieldType::FixedBytes(5),
    },
    FieldDesc {
        name: "Price",
        offset: 56,
        ty: FieldType::Decimal64Le,
    },
];

pub mod order_delete {
    pub const TEMPLATE_ID: u16 = 13102;
    pub const MIN_BLOCK_LEN: usize = 64;
    pub const BODY_LEN_OFFSET: usize = 0;
    pub const TEMPLATE_ID_OFFSET: usize = 2;
    pub const MSG_SEQ_NUM_OFFSET: usize = 4;
    pub const REQUEST_TIME_OFFSET: usize = 8;
    pub const TRANSACT_TIME_OFFSET: usize = 16;
    pub const SECURITY_ID_OFFSET: usize = 24;
    pub const TRD_REG_TSTIME_PRIORITY_OFFSET: usize = 32;
    pub const DISPLAY_QTY_OFFSET: usize = 40;
    pub const SIDE_OFFSET: usize = 48;
    pub const ORD_TYPE_OFFSET: usize = 49;
    pub const HHIINDICATOR_OFFSET: usize = 50;
    pub const PAD5_OFFSET: usize = 51;
    pub const PRICE_OFFSET: usize = 56;
}

pub const ORDERMASSDELETE_FIELDS: &[FieldDesc] = &[
    FieldDesc {
        name: "BodyLen",
        offset: 0,
        ty: FieldType::U16Le,
    },
    FieldDesc {
        name: "TemplateID",
        offset: 2,
        ty: FieldType::U16Le,
    },
    FieldDesc {
        name: "MsgSeqNum",
        offset: 4,
        ty: FieldType::U32Le,
    },
    FieldDesc {
        name: "SecurityID",
        offset: 8,
        ty: FieldType::I64Le,
    },
    FieldDesc {
        name: "TransactTime",
        offset: 16,
        ty: FieldType::U64Le,
    },
];

pub mod order_mass_delete {
    pub const TEMPLATE_ID: u16 = 13103;
    pub const MIN_BLOCK_LEN: usize = 24;
    pub const BODY_LEN_OFFSET: usize = 0;
    pub const TEMPLATE_ID_OFFSET: usize = 2;
    pub const MSG_SEQ_NUM_OFFSET: usize = 4;
    pub const SECURITY_ID_OFFSET: usize = 8;
    pub const TRANSACT_TIME_OFFSET: usize = 16;
}

pub const FULLORDEREXECUTION_FIELDS: &[FieldDesc] = &[
    FieldDesc {
        name: "BodyLen",
        offset: 0,
        ty: FieldType::U16Le,
    },
    FieldDesc {
        name: "TemplateID",
        offset: 2,
        ty: FieldType::U16Le,
    },
    FieldDesc {
        name: "MsgSeqNum",
        offset: 4,
        ty: FieldType::U32Le,
    },
    FieldDesc {
        name: "Side",
        offset: 8,
        ty: FieldType::U8,
    },
    FieldDesc {
        name: "OrdType",
        offset: 9,
        ty: FieldType::U8,
    },
    FieldDesc {
        name: "AlgorithmicTradeIndicator",
        offset: 10,
        ty: FieldType::U8,
    },
    FieldDesc {
        name: "HHIIndicator",
        offset: 11,
        ty: FieldType::I8,
    },
    FieldDesc {
        name: "TrdMatchID",
        offset: 12,
        ty: FieldType::U32Le,
    },
    FieldDesc {
        name: "Price",
        offset: 16,
        ty: FieldType::Decimal64Le,
    },
    FieldDesc {
        name: "TrdRegTSTimePriority",
        offset: 24,
        ty: FieldType::U64Le,
    },
    FieldDesc {
        name: "SecurityID",
        offset: 32,
        ty: FieldType::I64Le,
    },
    FieldDesc {
        name: "LastQty",
        offset: 40,
        ty: FieldType::Decimal64Le,
    },
    FieldDesc {
        name: "LastPx",
        offset: 48,
        ty: FieldType::Decimal64Le,
    },
];

pub mod full_order_execution {
    pub const TEMPLATE_ID: u16 = 13104;
    pub const MIN_BLOCK_LEN: usize = 56;
    pub const BODY_LEN_OFFSET: usize = 0;
    pub const TEMPLATE_ID_OFFSET: usize = 2;
    pub const MSG_SEQ_NUM_OFFSET: usize = 4;
    pub const SIDE_OFFSET: usize = 8;
    pub const ORD_TYPE_OFFSET: usize = 9;
    pub const ALGORITHMIC_TRADE_INDICATOR_OFFSET: usize = 10;
    pub const HHIINDICATOR_OFFSET: usize = 11;
    pub const TRD_MATCH_ID_OFFSET: usize = 12;
    pub const PRICE_OFFSET: usize = 16;
    pub const TRD_REG_TSTIME_PRIORITY_OFFSET: usize = 24;
    pub const SECURITY_ID_OFFSET: usize = 32;
    pub const LAST_QTY_OFFSET: usize = 40;
    pub const LAST_PX_OFFSET: usize = 48;
}

pub const PARTIALORDEREXECUTION_FIELDS: &[FieldDesc] = &[
    FieldDesc {
        name: "BodyLen",
        offset: 0,
        ty: FieldType::U16Le,
    },
    FieldDesc {
        name: "TemplateID",
        offset: 2,
        ty: FieldType::U16Le,
    },
    FieldDesc {
        name: "MsgSeqNum",
        offset: 4,
        ty: FieldType::U32Le,
    },
    FieldDesc {
        name: "Side",
        offset: 8,
        ty: FieldType::U8,
    },
    FieldDesc {
        name: "OrdType",
        offset: 9,
        ty: FieldType::U8,
    },
    FieldDesc {
        name: "AlgorithmicTradeIndicator",
        offset: 10,
        ty: FieldType::U8,
    },
    FieldDesc {
        name: "HHIIndicator",
        offset: 11,
        ty: FieldType::I8,
    },
    FieldDesc {
        name: "TrdMatchID",
        offset: 12,
        ty: FieldType::U32Le,
    },
    FieldDesc {
        name: "Price",
        offset: 16,
        ty: FieldType::Decimal64Le,
    },
    FieldDesc {
        name: "TrdRegTSTimePriority",
        offset: 24,
        ty: FieldType::U64Le,
    },
    FieldDesc {
        name: "SecurityID",
        offset: 32,
        ty: FieldType::I64Le,
    },
    FieldDesc {
        name: "LastQty",
        offset: 40,
        ty: FieldType::Decimal64Le,
    },
    FieldDesc {
        name: "LastPx",
        offset: 48,
        ty: FieldType::Decimal64Le,
    },
];

pub mod partial_order_execution {
    pub const TEMPLATE_ID: u16 = 13105;
    pub const MIN_BLOCK_LEN: usize = 56;
    pub const BODY_LEN_OFFSET: usize = 0;
    pub const TEMPLATE_ID_OFFSET: usize = 2;
    pub const MSG_SEQ_NUM_OFFSET: usize = 4;
    pub const SIDE_OFFSET: usize = 8;
    pub const ORD_TYPE_OFFSET: usize = 9;
    pub const ALGORITHMIC_TRADE_INDICATOR_OFFSET: usize = 10;
    pub const HHIINDICATOR_OFFSET: usize = 11;
    pub const TRD_MATCH_ID_OFFSET: usize = 12;
    pub const PRICE_OFFSET: usize = 16;
    pub const TRD_REG_TSTIME_PRIORITY_OFFSET: usize = 24;
    pub const SECURITY_ID_OFFSET: usize = 32;
    pub const LAST_QTY_OFFSET: usize = 40;
    pub const LAST_PX_OFFSET: usize = 48;
}

pub const ORDERMODIFYSAMEPRIO_FIELDS: &[FieldDesc] = &[
    FieldDesc {
        name: "BodyLen",
        offset: 0,
        ty: FieldType::U16Le,
    },
    FieldDesc {
        name: "TemplateID",
        offset: 2,
        ty: FieldType::U16Le,
    },
    FieldDesc {
        name: "MsgSeqNum",
        offset: 4,
        ty: FieldType::U32Le,
    },
    FieldDesc {
        name: "RequestTime",
        offset: 8,
        ty: FieldType::U64Le,
    },
    FieldDesc {
        name: "TransactTime",
        offset: 16,
        ty: FieldType::U64Le,
    },
    FieldDesc {
        name: "PrevDisplayQty",
        offset: 24,
        ty: FieldType::Decimal64Le,
    },
    FieldDesc {
        name: "SecurityID",
        offset: 32,
        ty: FieldType::I64Le,
    },
    FieldDesc {
        name: "TrdRegTSTimePriority",
        offset: 40,
        ty: FieldType::U64Le,
    },
    FieldDesc {
        name: "DisplayQty",
        offset: 48,
        ty: FieldType::Decimal64Le,
    },
    FieldDesc {
        name: "Side",
        offset: 56,
        ty: FieldType::U8,
    },
    FieldDesc {
        name: "OrdType",
        offset: 57,
        ty: FieldType::U8,
    },
    FieldDesc {
        name: "HHIIndicator",
        offset: 58,
        ty: FieldType::I8,
    },
    FieldDesc {
        name: "Pad5",
        offset: 59,
        ty: FieldType::FixedBytes(5),
    },
    FieldDesc {
        name: "Price",
        offset: 64,
        ty: FieldType::Decimal64Le,
    },
];

pub mod order_modify_same_prio {
    pub const TEMPLATE_ID: u16 = 13106;
    pub const MIN_BLOCK_LEN: usize = 72;
    pub const BODY_LEN_OFFSET: usize = 0;
    pub const TEMPLATE_ID_OFFSET: usize = 2;
    pub const MSG_SEQ_NUM_OFFSET: usize = 4;
    pub const REQUEST_TIME_OFFSET: usize = 8;
    pub const TRANSACT_TIME_OFFSET: usize = 16;
    pub const PREV_DISPLAY_QTY_OFFSET: usize = 24;
    pub const SECURITY_ID_OFFSET: usize = 32;
    pub const TRD_REG_TSTIME_PRIORITY_OFFSET: usize = 40;
    pub const DISPLAY_QTY_OFFSET: usize = 48;
    pub const SIDE_OFFSET: usize = 56;
    pub const ORD_TYPE_OFFSET: usize = 57;
    pub const HHIINDICATOR_OFFSET: usize = 58;
    pub const PAD5_OFFSET: usize = 59;
    pub const PRICE_OFFSET: usize = 64;
}

pub const TRADEREVERSAL_FIELDS: &[FieldDesc] = &[
    FieldDesc {
        name: "BodyLen",
        offset: 0,
        ty: FieldType::U16Le,
    },
    FieldDesc {
        name: "TemplateID",
        offset: 2,
        ty: FieldType::U16Le,
    },
    FieldDesc {
        name: "MsgSeqNum",
        offset: 4,
        ty: FieldType::U32Le,
    },
    FieldDesc {
        name: "SecurityID",
        offset: 8,
        ty: FieldType::I64Le,
    },
    FieldDesc {
        name: "TransactTime",
        offset: 16,
        ty: FieldType::U64Le,
    },
    FieldDesc {
        name: "LastQty",
        offset: 24,
        ty: FieldType::Decimal64Le,
    },
    FieldDesc {
        name: "LastPx",
        offset: 32,
        ty: FieldType::Decimal64Le,
    },
    FieldDesc {
        name: "TrdRegTSExecutionTime",
        offset: 40,
        ty: FieldType::U64Le,
    },
    FieldDesc {
        name: "TrdMatchID",
        offset: 48,
        ty: FieldType::U32Le,
    },
    FieldDesc {
        name: "TradeCondition",
        offset: 52,
        ty: FieldType::U16Le,
    },
    FieldDesc {
        name: "MDOriginType",
        offset: 54,
        ty: FieldType::U8,
    },
    FieldDesc {
        name: "NoMDEntries",
        offset: 55,
        ty: FieldType::U8,
    },
];

pub mod trade_reversal {
    pub const TEMPLATE_ID: u16 = 13200;
    pub const MIN_BLOCK_LEN: usize = 56;
    pub const BODY_LEN_OFFSET: usize = 0;
    pub const TEMPLATE_ID_OFFSET: usize = 2;
    pub const MSG_SEQ_NUM_OFFSET: usize = 4;
    pub const SECURITY_ID_OFFSET: usize = 8;
    pub const TRANSACT_TIME_OFFSET: usize = 16;
    pub const LAST_QTY_OFFSET: usize = 24;
    pub const LAST_PX_OFFSET: usize = 32;
    pub const TRD_REG_TSEXECUTION_TIME_OFFSET: usize = 40;
    pub const TRD_MATCH_ID_OFFSET: usize = 48;
    pub const TRADE_CONDITION_OFFSET: usize = 52;
    pub const MDORIGIN_TYPE_OFFSET: usize = 54;
    pub const NO_MDENTRIES_OFFSET: usize = 55;
}

pub const TRADEREPORT_FIELDS: &[FieldDesc] = &[
    FieldDesc {
        name: "BodyLen",
        offset: 0,
        ty: FieldType::U16Le,
    },
    FieldDesc {
        name: "TemplateID",
        offset: 2,
        ty: FieldType::U16Le,
    },
    FieldDesc {
        name: "MsgSeqNum",
        offset: 4,
        ty: FieldType::U32Le,
    },
    FieldDesc {
        name: "SecurityID",
        offset: 8,
        ty: FieldType::I64Le,
    },
    FieldDesc {
        name: "TransactTime",
        offset: 16,
        ty: FieldType::U64Le,
    },
    FieldDesc {
        name: "LastQty",
        offset: 24,
        ty: FieldType::Decimal64Le,
    },
    FieldDesc {
        name: "LastPx",
        offset: 32,
        ty: FieldType::Decimal64Le,
    },
    FieldDesc {
        name: "TrdMatchID",
        offset: 40,
        ty: FieldType::U32Le,
    },
    FieldDesc {
        name: "MatchType",
        offset: 44,
        ty: FieldType::U8,
    },
    FieldDesc {
        name: "MatchSubType",
        offset: 45,
        ty: FieldType::U8,
    },
    FieldDesc {
        name: "AlgorithmicTradeIndicator",
        offset: 46,
        ty: FieldType::U8,
    },
    FieldDesc {
        name: "Pad1",
        offset: 47,
        ty: FieldType::FixedBytes(1),
    },
    FieldDesc {
        name: "TradeCondition",
        offset: 48,
        ty: FieldType::U16Le,
    },
    FieldDesc {
        name: "Pad6",
        offset: 50,
        ty: FieldType::FixedBytes(6),
    },
];

pub mod trade_report {
    pub const TEMPLATE_ID: u16 = 13201;
    pub const MIN_BLOCK_LEN: usize = 56;
    pub const BODY_LEN_OFFSET: usize = 0;
    pub const TEMPLATE_ID_OFFSET: usize = 2;
    pub const MSG_SEQ_NUM_OFFSET: usize = 4;
    pub const SECURITY_ID_OFFSET: usize = 8;
    pub const TRANSACT_TIME_OFFSET: usize = 16;
    pub const LAST_QTY_OFFSET: usize = 24;
    pub const LAST_PX_OFFSET: usize = 32;
    pub const TRD_MATCH_ID_OFFSET: usize = 40;
    pub const MATCH_TYPE_OFFSET: usize = 44;
    pub const MATCH_SUB_TYPE_OFFSET: usize = 45;
    pub const ALGORITHMIC_TRADE_INDICATOR_OFFSET: usize = 46;
    pub const PAD1_OFFSET: usize = 47;
    pub const TRADE_CONDITION_OFFSET: usize = 48;
    pub const PAD6_OFFSET: usize = 50;
}

pub const EXECUTIONSUMMARY_FIELDS: &[FieldDesc] = &[
    FieldDesc {
        name: "BodyLen",
        offset: 0,
        ty: FieldType::U16Le,
    },
    FieldDesc {
        name: "TemplateID",
        offset: 2,
        ty: FieldType::U16Le,
    },
    FieldDesc {
        name: "MsgSeqNum",
        offset: 4,
        ty: FieldType::U32Le,
    },
    FieldDesc {
        name: "SecurityID",
        offset: 8,
        ty: FieldType::I64Le,
    },
    FieldDesc {
        name: "RequestTime",
        offset: 16,
        ty: FieldType::U64Le,
    },
    FieldDesc {
        name: "ExecID",
        offset: 24,
        ty: FieldType::U64Le,
    },
    FieldDesc {
        name: "LastQty",
        offset: 32,
        ty: FieldType::Decimal64Le,
    },
    FieldDesc {
        name: "AggressorSide",
        offset: 40,
        ty: FieldType::U8,
    },
    FieldDesc {
        name: "Pad1",
        offset: 41,
        ty: FieldType::FixedBytes(1),
    },
    FieldDesc {
        name: "TradeCondition",
        offset: 42,
        ty: FieldType::U16Le,
    },
    FieldDesc {
        name: "TradingHHIIndicator",
        offset: 44,
        ty: FieldType::U8,
    },
    FieldDesc {
        name: "Pad3",
        offset: 45,
        ty: FieldType::FixedBytes(3),
    },
    FieldDesc {
        name: "LastPx",
        offset: 48,
        ty: FieldType::Decimal64Le,
    },
    FieldDesc {
        name: "TrdRegTSPrevTimePriority",
        offset: 56,
        ty: FieldType::U64Le,
    },
    FieldDesc {
        name: "DisplayQty",
        offset: 64,
        ty: FieldType::Decimal64Le,
    },
    FieldDesc {
        name: "Price",
        offset: 72,
        ty: FieldType::Decimal64Le,
    },
    FieldDesc {
        name: "RestingHiddenQty",
        offset: 80,
        ty: FieldType::Decimal64Le,
    },
    FieldDesc {
        name: "RestingCxlQty",
        offset: 88,
        ty: FieldType::Decimal64Le,
    },
    FieldDesc {
        name: "AggressorTime",
        offset: 96,
        ty: FieldType::U64Le,
    },
];

pub mod execution_summary {
    pub const TEMPLATE_ID: u16 = 13202;
    pub const MIN_BLOCK_LEN: usize = 104;
    pub const BODY_LEN_OFFSET: usize = 0;
    pub const TEMPLATE_ID_OFFSET: usize = 2;
    pub const MSG_SEQ_NUM_OFFSET: usize = 4;
    pub const SECURITY_ID_OFFSET: usize = 8;
    pub const REQUEST_TIME_OFFSET: usize = 16;
    pub const EXEC_ID_OFFSET: usize = 24;
    pub const LAST_QTY_OFFSET: usize = 32;
    pub const AGGRESSOR_SIDE_OFFSET: usize = 40;
    pub const PAD1_OFFSET: usize = 41;
    pub const TRADE_CONDITION_OFFSET: usize = 42;
    pub const TRADING_HHIINDICATOR_OFFSET: usize = 44;
    pub const PAD3_OFFSET: usize = 45;
    pub const LAST_PX_OFFSET: usize = 48;
    pub const TRD_REG_TSPREV_TIME_PRIORITY_OFFSET: usize = 56;
    pub const DISPLAY_QTY_OFFSET: usize = 64;
    pub const PRICE_OFFSET: usize = 72;
    pub const RESTING_HIDDEN_QTY_OFFSET: usize = 80;
    pub const RESTING_CXL_QTY_OFFSET: usize = 88;
    pub const AGGRESSOR_TIME_OFFSET: usize = 96;
}

pub const TESTRADEREPORT_FIELDS: &[FieldDesc] = &[
    FieldDesc {
        name: "BodyLen",
        offset: 0,
        ty: FieldType::U16Le,
    },
    FieldDesc {
        name: "TemplateID",
        offset: 2,
        ty: FieldType::U16Le,
    },
    FieldDesc {
        name: "MsgSeqNum",
        offset: 4,
        ty: FieldType::U32Le,
    },
    FieldDesc {
        name: "SecurityID",
        offset: 8,
        ty: FieldType::I64Le,
    },
    FieldDesc {
        name: "TransactTime",
        offset: 16,
        ty: FieldType::U64Le,
    },
    FieldDesc {
        name: "LastQty",
        offset: 24,
        ty: FieldType::Decimal64Le,
    },
    FieldDesc {
        name: "LastPx",
        offset: 32,
        ty: FieldType::Decimal64Le,
    },
    FieldDesc {
        name: "TrdMatchID",
        offset: 40,
        ty: FieldType::U32Le,
    },
    FieldDesc {
        name: "TrdType",
        offset: 44,
        ty: FieldType::U16Le,
    },
    FieldDesc {
        name: "TradeCondition",
        offset: 46,
        ty: FieldType::U16Le,
    },
    FieldDesc {
        name: "MultiLegReportingType",
        offset: 48,
        ty: FieldType::U8,
    },
    FieldDesc {
        name: "MultiLegPriceModel",
        offset: 49,
        ty: FieldType::U8,
    },
    FieldDesc {
        name: "Pad6",
        offset: 50,
        ty: FieldType::FixedBytes(6),
    },
    FieldDesc {
        name: "NonDisclosedTradeVolume",
        offset: 56,
        ty: FieldType::Decimal64Le,
    },
    FieldDesc {
        name: "TransBkdTime",
        offset: 64,
        ty: FieldType::U64Le,
    },
    FieldDesc {
        name: "NumberOfBuySides",
        offset: 72,
        ty: FieldType::U16Le,
    },
    FieldDesc {
        name: "NumberOfSellSides",
        offset: 74,
        ty: FieldType::U16Le,
    },
    FieldDesc {
        name: "Pad4",
        offset: 76,
        ty: FieldType::FixedBytes(4),
    },
];

pub mod t_e_s_trade_report {
    pub const TEMPLATE_ID: u16 = 13203;
    pub const MIN_BLOCK_LEN: usize = 80;
    pub const BODY_LEN_OFFSET: usize = 0;
    pub const TEMPLATE_ID_OFFSET: usize = 2;
    pub const MSG_SEQ_NUM_OFFSET: usize = 4;
    pub const SECURITY_ID_OFFSET: usize = 8;
    pub const TRANSACT_TIME_OFFSET: usize = 16;
    pub const LAST_QTY_OFFSET: usize = 24;
    pub const LAST_PX_OFFSET: usize = 32;
    pub const TRD_MATCH_ID_OFFSET: usize = 40;
    pub const TRD_TYPE_OFFSET: usize = 44;
    pub const TRADE_CONDITION_OFFSET: usize = 46;
    pub const MULTI_LEG_REPORTING_TYPE_OFFSET: usize = 48;
    pub const MULTI_LEG_PRICE_MODEL_OFFSET: usize = 49;
    pub const PAD6_OFFSET: usize = 50;
    pub const NON_DISCLOSED_TRADE_VOLUME_OFFSET: usize = 56;
    pub const TRANS_BKD_TIME_OFFSET: usize = 64;
    pub const NUMBER_OF_BUY_SIDES_OFFSET: usize = 72;
    pub const NUMBER_OF_SELL_SIDES_OFFSET: usize = 74;
    pub const PAD4_OFFSET: usize = 76;
}

pub const PRODUCTSTATECHANGE_FIELDS: &[FieldDesc] = &[
    FieldDesc {
        name: "BodyLen",
        offset: 0,
        ty: FieldType::U16Le,
    },
    FieldDesc {
        name: "TemplateID",
        offset: 2,
        ty: FieldType::U16Le,
    },
    FieldDesc {
        name: "MsgSeqNum",
        offset: 4,
        ty: FieldType::U32Le,
    },
    FieldDesc {
        name: "TradingSessionID",
        offset: 8,
        ty: FieldType::U8,
    },
    FieldDesc {
        name: "TradingSessionSubID",
        offset: 9,
        ty: FieldType::U8,
    },
    FieldDesc {
        name: "TradSesStatus",
        offset: 10,
        ty: FieldType::U8,
    },
    FieldDesc {
        name: "MarketCondition",
        offset: 11,
        ty: FieldType::U8,
    },
    FieldDesc {
        name: "FastMarketIndicator",
        offset: 12,
        ty: FieldType::U8,
    },
    FieldDesc {
        name: "TESTradSesStatus",
        offset: 13,
        ty: FieldType::U8,
    },
    FieldDesc {
        name: "Pad2",
        offset: 14,
        ty: FieldType::FixedBytes(2),
    },
    FieldDesc {
        name: "TransactTime",
        offset: 16,
        ty: FieldType::U64Le,
    },
];

pub mod product_state_change {
    pub const TEMPLATE_ID: u16 = 13300;
    pub const MIN_BLOCK_LEN: usize = 24;
    pub const BODY_LEN_OFFSET: usize = 0;
    pub const TEMPLATE_ID_OFFSET: usize = 2;
    pub const MSG_SEQ_NUM_OFFSET: usize = 4;
    pub const TRADING_SESSION_ID_OFFSET: usize = 8;
    pub const TRADING_SESSION_SUB_ID_OFFSET: usize = 9;
    pub const TRAD_SES_STATUS_OFFSET: usize = 10;
    pub const MARKET_CONDITION_OFFSET: usize = 11;
    pub const FAST_MARKET_INDICATOR_OFFSET: usize = 12;
    pub const TESTRAD_SES_STATUS_OFFSET: usize = 13;
    pub const PAD2_OFFSET: usize = 14;
    pub const TRANSACT_TIME_OFFSET: usize = 16;
}

pub const INSTRUMENTSTATECHANGE_FIELDS: &[FieldDesc] = &[
    FieldDesc {
        name: "BodyLen",
        offset: 0,
        ty: FieldType::U16Le,
    },
    FieldDesc {
        name: "TemplateID",
        offset: 2,
        ty: FieldType::U16Le,
    },
    FieldDesc {
        name: "MsgSeqNum",
        offset: 4,
        ty: FieldType::U32Le,
    },
    FieldDesc {
        name: "SecurityID",
        offset: 8,
        ty: FieldType::I64Le,
    },
    FieldDesc {
        name: "SecurityStatus",
        offset: 16,
        ty: FieldType::U8,
    },
    FieldDesc {
        name: "SecurityTradingStatus",
        offset: 17,
        ty: FieldType::U8,
    },
    FieldDesc {
        name: "MarketCondition",
        offset: 18,
        ty: FieldType::U8,
    },
    FieldDesc {
        name: "FastMarketIndicator",
        offset: 19,
        ty: FieldType::U8,
    },
    FieldDesc {
        name: "SecurityTradingEvent",
        offset: 20,
        ty: FieldType::U8,
    },
    FieldDesc {
        name: "SoldOutIndicator",
        offset: 21,
        ty: FieldType::U8,
    },
    FieldDesc {
        name: "Pad2",
        offset: 22,
        ty: FieldType::FixedBytes(2),
    },
    FieldDesc {
        name: "HighPx",
        offset: 24,
        ty: FieldType::Decimal64Le,
    },
    FieldDesc {
        name: "LowPx",
        offset: 32,
        ty: FieldType::Decimal64Le,
    },
    FieldDesc {
        name: "TransactTime",
        offset: 40,
        ty: FieldType::U64Le,
    },
    FieldDesc {
        name: "TESSecurityStatus",
        offset: 48,
        ty: FieldType::U8,
    },
    FieldDesc {
        name: "Pad7",
        offset: 49,
        ty: FieldType::FixedBytes(7),
    },
];

pub mod instrument_state_change {
    pub const TEMPLATE_ID: u16 = 13301;
    pub const MIN_BLOCK_LEN: usize = 56;
    pub const BODY_LEN_OFFSET: usize = 0;
    pub const TEMPLATE_ID_OFFSET: usize = 2;
    pub const MSG_SEQ_NUM_OFFSET: usize = 4;
    pub const SECURITY_ID_OFFSET: usize = 8;
    pub const SECURITY_STATUS_OFFSET: usize = 16;
    pub const SECURITY_TRADING_STATUS_OFFSET: usize = 17;
    pub const MARKET_CONDITION_OFFSET: usize = 18;
    pub const FAST_MARKET_INDICATOR_OFFSET: usize = 19;
    pub const SECURITY_TRADING_EVENT_OFFSET: usize = 20;
    pub const SOLD_OUT_INDICATOR_OFFSET: usize = 21;
    pub const PAD2_OFFSET: usize = 22;
    pub const HIGH_PX_OFFSET: usize = 24;
    pub const LOW_PX_OFFSET: usize = 32;
    pub const TRANSACT_TIME_OFFSET: usize = 40;
    pub const TESSECURITY_STATUS_OFFSET: usize = 48;
    pub const PAD7_OFFSET: usize = 49;
}

pub const MASSINSTRUMENTSTATECHANGE_FIELDS: &[FieldDesc] = &[
    FieldDesc {
        name: "BodyLen",
        offset: 0,
        ty: FieldType::U16Le,
    },
    FieldDesc {
        name: "TemplateID",
        offset: 2,
        ty: FieldType::U16Le,
    },
    FieldDesc {
        name: "MsgSeqNum",
        offset: 4,
        ty: FieldType::U32Le,
    },
    FieldDesc {
        name: "InstrumentScopeProductComplex",
        offset: 8,
        ty: FieldType::U8,
    },
    FieldDesc {
        name: "SecurityMassStatus",
        offset: 9,
        ty: FieldType::U8,
    },
    FieldDesc {
        name: "SecurityMassTradingStatus",
        offset: 10,
        ty: FieldType::U8,
    },
    FieldDesc {
        name: "MassMarketCondition",
        offset: 11,
        ty: FieldType::U8,
    },
    FieldDesc {
        name: "FastMarketIndicator",
        offset: 12,
        ty: FieldType::U8,
    },
    FieldDesc {
        name: "SecurityMassTradingEvent",
        offset: 13,
        ty: FieldType::U8,
    },
    FieldDesc {
        name: "MassSoldOutIndicator",
        offset: 14,
        ty: FieldType::U8,
    },
    FieldDesc {
        name: "TESSecurityMassStatus",
        offset: 15,
        ty: FieldType::U8,
    },
    FieldDesc {
        name: "TransactTime",
        offset: 16,
        ty: FieldType::U64Le,
    },
    FieldDesc {
        name: "LastFragment",
        offset: 24,
        ty: FieldType::U8,
    },
    FieldDesc {
        name: "NoRelatedSym",
        offset: 25,
        ty: FieldType::U8,
    },
    FieldDesc {
        name: "Pad6",
        offset: 26,
        ty: FieldType::FixedBytes(6),
    },
];

pub mod mass_instrument_state_change {
    pub const TEMPLATE_ID: u16 = 13302;
    pub const MIN_BLOCK_LEN: usize = 32;
    pub const BODY_LEN_OFFSET: usize = 0;
    pub const TEMPLATE_ID_OFFSET: usize = 2;
    pub const MSG_SEQ_NUM_OFFSET: usize = 4;
    pub const INSTRUMENT_SCOPE_PRODUCT_COMPLEX_OFFSET: usize = 8;
    pub const SECURITY_MASS_STATUS_OFFSET: usize = 9;
    pub const SECURITY_MASS_TRADING_STATUS_OFFSET: usize = 10;
    pub const MASS_MARKET_CONDITION_OFFSET: usize = 11;
    pub const FAST_MARKET_INDICATOR_OFFSET: usize = 12;
    pub const SECURITY_MASS_TRADING_EVENT_OFFSET: usize = 13;
    pub const MASS_SOLD_OUT_INDICATOR_OFFSET: usize = 14;
    pub const TESSECURITY_MASS_STATUS_OFFSET: usize = 15;
    pub const TRANSACT_TIME_OFFSET: usize = 16;
    pub const LAST_FRAGMENT_OFFSET: usize = 24;
    pub const NO_RELATED_SYM_OFFSET: usize = 25;
    pub const PAD6_OFFSET: usize = 26;
}

pub const ADDCOMPLEXINSTRUMENT_FIELDS: &[FieldDesc] = &[
    FieldDesc {
        name: "BodyLen",
        offset: 0,
        ty: FieldType::U16Le,
    },
    FieldDesc {
        name: "TemplateID",
        offset: 2,
        ty: FieldType::U16Le,
    },
    FieldDesc {
        name: "MsgSeqNum",
        offset: 4,
        ty: FieldType::U32Le,
    },
    FieldDesc {
        name: "SecurityID",
        offset: 8,
        ty: FieldType::I64Le,
    },
    FieldDesc {
        name: "TransactTime",
        offset: 16,
        ty: FieldType::U64Le,
    },
    FieldDesc {
        name: "SecurityDesc",
        offset: 24,
        ty: FieldType::FixedBytes(40),
    },
    FieldDesc {
        name: "SecuritySubType",
        offset: 64,
        ty: FieldType::I32Le,
    },
    FieldDesc {
        name: "ProductComplex",
        offset: 68,
        ty: FieldType::U8,
    },
    FieldDesc {
        name: "ImpliedMarketIndicator",
        offset: 69,
        ty: FieldType::U8,
    },
    FieldDesc {
        name: "QuantityScalingFactor",
        offset: 70,
        ty: FieldType::U16Le,
    },
    FieldDesc {
        name: "LegRatioMultiplier",
        offset: 72,
        ty: FieldType::U32Le,
    },
    FieldDesc {
        name: "NoLegs",
        offset: 76,
        ty: FieldType::U8,
    },
    FieldDesc {
        name: "Pad2",
        offset: 77,
        ty: FieldType::FixedBytes(2),
    },
    FieldDesc {
        name: "LastFragment",
        offset: 79,
        ty: FieldType::U8,
    },
];

pub mod add_complex_instrument {
    pub const TEMPLATE_ID: u16 = 13400;
    pub const MIN_BLOCK_LEN: usize = 80;
    pub const BODY_LEN_OFFSET: usize = 0;
    pub const TEMPLATE_ID_OFFSET: usize = 2;
    pub const MSG_SEQ_NUM_OFFSET: usize = 4;
    pub const SECURITY_ID_OFFSET: usize = 8;
    pub const TRANSACT_TIME_OFFSET: usize = 16;
    pub const SECURITY_DESC_OFFSET: usize = 24;
    pub const SECURITY_SUB_TYPE_OFFSET: usize = 64;
    pub const PRODUCT_COMPLEX_OFFSET: usize = 68;
    pub const IMPLIED_MARKET_INDICATOR_OFFSET: usize = 69;
    pub const QUANTITY_SCALING_FACTOR_OFFSET: usize = 70;
    pub const LEG_RATIO_MULTIPLIER_OFFSET: usize = 72;
    pub const NO_LEGS_OFFSET: usize = 76;
    pub const PAD2_OFFSET: usize = 77;
    pub const LAST_FRAGMENT_OFFSET: usize = 79;
}

pub const ADDFLEXIBLEINSTRUMENT_FIELDS: &[FieldDesc] = &[
    FieldDesc {
        name: "BodyLen",
        offset: 0,
        ty: FieldType::U16Le,
    },
    FieldDesc {
        name: "TemplateID",
        offset: 2,
        ty: FieldType::U16Le,
    },
    FieldDesc {
        name: "MsgSeqNum",
        offset: 4,
        ty: FieldType::U32Le,
    },
    FieldDesc {
        name: "SecurityID",
        offset: 8,
        ty: FieldType::I64Le,
    },
    FieldDesc {
        name: "TransactTime",
        offset: 16,
        ty: FieldType::U64Le,
    },
    FieldDesc {
        name: "SecurityDesc",
        offset: 24,
        ty: FieldType::FixedBytes(40),
    },
    FieldDesc {
        name: "SecurityType",
        offset: 64,
        ty: FieldType::U8,
    },
    FieldDesc {
        name: "PutOrCall",
        offset: 65,
        ty: FieldType::U8,
    },
    FieldDesc {
        name: "ExerciseStyle",
        offset: 66,
        ty: FieldType::U8,
    },
    FieldDesc {
        name: "SettlMethod",
        offset: 67,
        ty: FieldType::U8,
    },
    FieldDesc {
        name: "MaturityDate",
        offset: 68,
        ty: FieldType::U32Le,
    },
    FieldDesc {
        name: "StrikePrice",
        offset: 72,
        ty: FieldType::Decimal64Le,
    },
    FieldDesc {
        name: "OptAttribute",
        offset: 80,
        ty: FieldType::U32Le,
    },
    FieldDesc {
        name: "ContractDate",
        offset: 84,
        ty: FieldType::U32Le,
    },
    FieldDesc {
        name: "SecurityReferenceDataSupplement",
        offset: 88,
        ty: FieldType::U32Le,
    },
    FieldDesc {
        name: "Pad4",
        offset: 92,
        ty: FieldType::FixedBytes(4),
    },
];

pub mod add_flexible_instrument {
    pub const TEMPLATE_ID: u16 = 13401;
    pub const MIN_BLOCK_LEN: usize = 96;
    pub const BODY_LEN_OFFSET: usize = 0;
    pub const TEMPLATE_ID_OFFSET: usize = 2;
    pub const MSG_SEQ_NUM_OFFSET: usize = 4;
    pub const SECURITY_ID_OFFSET: usize = 8;
    pub const TRANSACT_TIME_OFFSET: usize = 16;
    pub const SECURITY_DESC_OFFSET: usize = 24;
    pub const SECURITY_TYPE_OFFSET: usize = 64;
    pub const PUT_OR_CALL_OFFSET: usize = 65;
    pub const EXERCISE_STYLE_OFFSET: usize = 66;
    pub const SETTL_METHOD_OFFSET: usize = 67;
    pub const MATURITY_DATE_OFFSET: usize = 68;
    pub const STRIKE_PRICE_OFFSET: usize = 72;
    pub const OPT_ATTRIBUTE_OFFSET: usize = 80;
    pub const CONTRACT_DATE_OFFSET: usize = 84;
    pub const SECURITY_REFERENCE_DATA_SUPPLEMENT_OFFSET: usize = 88;
    pub const PAD4_OFFSET: usize = 92;
}

pub const ADDSCALEDSIMPLEINSTRUMENT_FIELDS: &[FieldDesc] = &[
    FieldDesc {
        name: "BodyLen",
        offset: 0,
        ty: FieldType::U16Le,
    },
    FieldDesc {
        name: "TemplateID",
        offset: 2,
        ty: FieldType::U16Le,
    },
    FieldDesc {
        name: "MsgSeqNum",
        offset: 4,
        ty: FieldType::U32Le,
    },
    FieldDesc {
        name: "SecurityID",
        offset: 8,
        ty: FieldType::I64Le,
    },
    FieldDesc {
        name: "TransactTime",
        offset: 16,
        ty: FieldType::U64Le,
    },
    FieldDesc {
        name: "SecurityDesc",
        offset: 24,
        ty: FieldType::FixedBytes(40),
    },
    FieldDesc {
        name: "SecurityType",
        offset: 64,
        ty: FieldType::U8,
    },
    FieldDesc {
        name: "Pad1",
        offset: 65,
        ty: FieldType::FixedBytes(1),
    },
    FieldDesc {
        name: "QuantityScalingFactor",
        offset: 66,
        ty: FieldType::U16Le,
    },
    FieldDesc {
        name: "Pad4",
        offset: 68,
        ty: FieldType::FixedBytes(4),
    },
    FieldDesc {
        name: "RelatedSecurityID",
        offset: 72,
        ty: FieldType::I64Le,
    },
];

pub mod add_scaled_simple_instrument {
    pub const TEMPLATE_ID: u16 = 13402;
    pub const MIN_BLOCK_LEN: usize = 80;
    pub const BODY_LEN_OFFSET: usize = 0;
    pub const TEMPLATE_ID_OFFSET: usize = 2;
    pub const MSG_SEQ_NUM_OFFSET: usize = 4;
    pub const SECURITY_ID_OFFSET: usize = 8;
    pub const TRANSACT_TIME_OFFSET: usize = 16;
    pub const SECURITY_DESC_OFFSET: usize = 24;
    pub const SECURITY_TYPE_OFFSET: usize = 64;
    pub const PAD1_OFFSET: usize = 65;
    pub const QUANTITY_SCALING_FACTOR_OFFSET: usize = 66;
    pub const PAD4_OFFSET: usize = 68;
    pub const RELATED_SECURITY_ID_OFFSET: usize = 72;
}

pub const AUCTIONBBO_FIELDS: &[FieldDesc] = &[
    FieldDesc {
        name: "BodyLen",
        offset: 0,
        ty: FieldType::U16Le,
    },
    FieldDesc {
        name: "TemplateID",
        offset: 2,
        ty: FieldType::U16Le,
    },
    FieldDesc {
        name: "MsgSeqNum",
        offset: 4,
        ty: FieldType::U32Le,
    },
    FieldDesc {
        name: "TransactTime",
        offset: 8,
        ty: FieldType::U64Le,
    },
    FieldDesc {
        name: "SecurityID",
        offset: 16,
        ty: FieldType::I64Le,
    },
    FieldDesc {
        name: "BidPx",
        offset: 24,
        ty: FieldType::Decimal64Le,
    },
    FieldDesc {
        name: "OfferPx",
        offset: 32,
        ty: FieldType::Decimal64Le,
    },
    FieldDesc {
        name: "BidSize",
        offset: 40,
        ty: FieldType::Decimal64Le,
    },
    FieldDesc {
        name: "OfferSize",
        offset: 48,
        ty: FieldType::Decimal64Le,
    },
    FieldDesc {
        name: "PotentialSecurityTradingEvent",
        offset: 56,
        ty: FieldType::U8,
    },
    FieldDesc {
        name: "BidOrdType",
        offset: 57,
        ty: FieldType::U8,
    },
    FieldDesc {
        name: "OfferOrdType",
        offset: 58,
        ty: FieldType::U8,
    },
    FieldDesc {
        name: "Pad5",
        offset: 59,
        ty: FieldType::FixedBytes(5),
    },
];

pub mod auction_b_b_o {
    pub const TEMPLATE_ID: u16 = 13500;
    pub const MIN_BLOCK_LEN: usize = 64;
    pub const BODY_LEN_OFFSET: usize = 0;
    pub const TEMPLATE_ID_OFFSET: usize = 2;
    pub const MSG_SEQ_NUM_OFFSET: usize = 4;
    pub const TRANSACT_TIME_OFFSET: usize = 8;
    pub const SECURITY_ID_OFFSET: usize = 16;
    pub const BID_PX_OFFSET: usize = 24;
    pub const OFFER_PX_OFFSET: usize = 32;
    pub const BID_SIZE_OFFSET: usize = 40;
    pub const OFFER_SIZE_OFFSET: usize = 48;
    pub const POTENTIAL_SECURITY_TRADING_EVENT_OFFSET: usize = 56;
    pub const BID_ORD_TYPE_OFFSET: usize = 57;
    pub const OFFER_ORD_TYPE_OFFSET: usize = 58;
    pub const PAD5_OFFSET: usize = 59;
}

pub const AUCTIONCLEARINGPRICE_FIELDS: &[FieldDesc] = &[
    FieldDesc {
        name: "BodyLen",
        offset: 0,
        ty: FieldType::U16Le,
    },
    FieldDesc {
        name: "TemplateID",
        offset: 2,
        ty: FieldType::U16Le,
    },
    FieldDesc {
        name: "MsgSeqNum",
        offset: 4,
        ty: FieldType::U32Le,
    },
    FieldDesc {
        name: "TransactTime",
        offset: 8,
        ty: FieldType::U64Le,
    },
    FieldDesc {
        name: "SecurityID",
        offset: 16,
        ty: FieldType::I64Le,
    },
    FieldDesc {
        name: "LastPx",
        offset: 24,
        ty: FieldType::Decimal64Le,
    },
    FieldDesc {
        name: "LastQty",
        offset: 32,
        ty: FieldType::Decimal64Le,
    },
    FieldDesc {
        name: "ImbalanceQty",
        offset: 40,
        ty: FieldType::Decimal64Le,
    },
    FieldDesc {
        name: "SecurityTradingStatus",
        offset: 48,
        ty: FieldType::U8,
    },
    FieldDesc {
        name: "PotentialSecurityTradingEvent",
        offset: 49,
        ty: FieldType::U8,
    },
    FieldDesc {
        name: "Pad6",
        offset: 50,
        ty: FieldType::FixedBytes(6),
    },
];

pub mod auction_clearing_price {
    pub const TEMPLATE_ID: u16 = 13501;
    pub const MIN_BLOCK_LEN: usize = 56;
    pub const BODY_LEN_OFFSET: usize = 0;
    pub const TEMPLATE_ID_OFFSET: usize = 2;
    pub const MSG_SEQ_NUM_OFFSET: usize = 4;
    pub const TRANSACT_TIME_OFFSET: usize = 8;
    pub const SECURITY_ID_OFFSET: usize = 16;
    pub const LAST_PX_OFFSET: usize = 24;
    pub const LAST_QTY_OFFSET: usize = 32;
    pub const IMBALANCE_QTY_OFFSET: usize = 40;
    pub const SECURITY_TRADING_STATUS_OFFSET: usize = 48;
    pub const POTENTIAL_SECURITY_TRADING_EVENT_OFFSET: usize = 49;
    pub const PAD6_OFFSET: usize = 50;
}

pub const CROSSREQUEST_FIELDS: &[FieldDesc] = &[
    FieldDesc {
        name: "BodyLen",
        offset: 0,
        ty: FieldType::U16Le,
    },
    FieldDesc {
        name: "TemplateID",
        offset: 2,
        ty: FieldType::U16Le,
    },
    FieldDesc {
        name: "MsgSeqNum",
        offset: 4,
        ty: FieldType::U32Le,
    },
    FieldDesc {
        name: "SecurityID",
        offset: 8,
        ty: FieldType::I64Le,
    },
    FieldDesc {
        name: "LastPx",
        offset: 16,
        ty: FieldType::Decimal64Le,
    },
    FieldDesc {
        name: "LastQty",
        offset: 24,
        ty: FieldType::Decimal64Le,
    },
    FieldDesc {
        name: "Side",
        offset: 32,
        ty: FieldType::U8,
    },
    FieldDesc {
        name: "CrossRequestType",
        offset: 33,
        ty: FieldType::U8,
    },
    FieldDesc {
        name: "InputSource",
        offset: 34,
        ty: FieldType::U8,
    },
    FieldDesc {
        name: "Pad5",
        offset: 35,
        ty: FieldType::FixedBytes(5),
    },
    FieldDesc {
        name: "TransactTime",
        offset: 40,
        ty: FieldType::U64Le,
    },
];

pub mod cross_request {
    pub const TEMPLATE_ID: u16 = 13502;
    pub const MIN_BLOCK_LEN: usize = 48;
    pub const BODY_LEN_OFFSET: usize = 0;
    pub const TEMPLATE_ID_OFFSET: usize = 2;
    pub const MSG_SEQ_NUM_OFFSET: usize = 4;
    pub const SECURITY_ID_OFFSET: usize = 8;
    pub const LAST_PX_OFFSET: usize = 16;
    pub const LAST_QTY_OFFSET: usize = 24;
    pub const SIDE_OFFSET: usize = 32;
    pub const CROSS_REQUEST_TYPE_OFFSET: usize = 33;
    pub const INPUT_SOURCE_OFFSET: usize = 34;
    pub const PAD5_OFFSET: usize = 35;
    pub const TRANSACT_TIME_OFFSET: usize = 40;
}

pub const QUOTEREQUEST_FIELDS: &[FieldDesc] = &[
    FieldDesc {
        name: "BodyLen",
        offset: 0,
        ty: FieldType::U16Le,
    },
    FieldDesc {
        name: "TemplateID",
        offset: 2,
        ty: FieldType::U16Le,
    },
    FieldDesc {
        name: "MsgSeqNum",
        offset: 4,
        ty: FieldType::U32Le,
    },
    FieldDesc {
        name: "SecurityID",
        offset: 8,
        ty: FieldType::I64Le,
    },
    FieldDesc {
        name: "LastQty",
        offset: 16,
        ty: FieldType::Decimal64Le,
    },
    FieldDesc {
        name: "Side",
        offset: 24,
        ty: FieldType::U8,
    },
    FieldDesc {
        name: "Pad7",
        offset: 25,
        ty: FieldType::FixedBytes(7),
    },
    FieldDesc {
        name: "TransactTime",
        offset: 32,
        ty: FieldType::U64Le,
    },
];

pub mod quote_request {
    pub const TEMPLATE_ID: u16 = 13503;
    pub const MIN_BLOCK_LEN: usize = 40;
    pub const BODY_LEN_OFFSET: usize = 0;
    pub const TEMPLATE_ID_OFFSET: usize = 2;
    pub const MSG_SEQ_NUM_OFFSET: usize = 4;
    pub const SECURITY_ID_OFFSET: usize = 8;
    pub const LAST_QTY_OFFSET: usize = 16;
    pub const SIDE_OFFSET: usize = 24;
    pub const PAD7_OFFSET: usize = 25;
    pub const TRANSACT_TIME_OFFSET: usize = 32;
}

pub const TOPOFBOOK_FIELDS: &[FieldDesc] = &[
    FieldDesc {
        name: "BodyLen",
        offset: 0,
        ty: FieldType::U16Le,
    },
    FieldDesc {
        name: "TemplateID",
        offset: 2,
        ty: FieldType::U16Le,
    },
    FieldDesc {
        name: "MsgSeqNum",
        offset: 4,
        ty: FieldType::U32Le,
    },
    FieldDesc {
        name: "TransactTime",
        offset: 8,
        ty: FieldType::U64Le,
    },
    FieldDesc {
        name: "SecurityID",
        offset: 16,
        ty: FieldType::I64Le,
    },
    FieldDesc {
        name: "BidPx",
        offset: 24,
        ty: FieldType::Decimal64Le,
    },
    FieldDesc {
        name: "OfferPx",
        offset: 32,
        ty: FieldType::Decimal64Le,
    },
    FieldDesc {
        name: "BidSize",
        offset: 40,
        ty: FieldType::Decimal64Le,
    },
    FieldDesc {
        name: "OfferSize",
        offset: 48,
        ty: FieldType::Decimal64Le,
    },
    FieldDesc {
        name: "NumberOfBuyOrders",
        offset: 56,
        ty: FieldType::U16Le,
    },
    FieldDesc {
        name: "NumberOfSellOrders",
        offset: 58,
        ty: FieldType::U16Le,
    },
    FieldDesc {
        name: "Pad4",
        offset: 60,
        ty: FieldType::FixedBytes(4),
    },
];

pub mod top_of_book {
    pub const TEMPLATE_ID: u16 = 13504;
    pub const MIN_BLOCK_LEN: usize = 64;
    pub const BODY_LEN_OFFSET: usize = 0;
    pub const TEMPLATE_ID_OFFSET: usize = 2;
    pub const MSG_SEQ_NUM_OFFSET: usize = 4;
    pub const TRANSACT_TIME_OFFSET: usize = 8;
    pub const SECURITY_ID_OFFSET: usize = 16;
    pub const BID_PX_OFFSET: usize = 24;
    pub const OFFER_PX_OFFSET: usize = 32;
    pub const BID_SIZE_OFFSET: usize = 40;
    pub const OFFER_SIZE_OFFSET: usize = 48;
    pub const NUMBER_OF_BUY_ORDERS_OFFSET: usize = 56;
    pub const NUMBER_OF_SELL_ORDERS_OFFSET: usize = 58;
    pub const PAD4_OFFSET: usize = 60;
}

pub const PRODUCTSUMMARY_FIELDS: &[FieldDesc] = &[
    FieldDesc {
        name: "BodyLen",
        offset: 0,
        ty: FieldType::U16Le,
    },
    FieldDesc {
        name: "TemplateID",
        offset: 2,
        ty: FieldType::U16Le,
    },
    FieldDesc {
        name: "MsgSeqNum",
        offset: 4,
        ty: FieldType::U32Le,
    },
    FieldDesc {
        name: "LastMsgSeqNumProcessed",
        offset: 8,
        ty: FieldType::U32Le,
    },
    FieldDesc {
        name: "TradingSessionID",
        offset: 12,
        ty: FieldType::U8,
    },
    FieldDesc {
        name: "TradingSessionSubID",
        offset: 13,
        ty: FieldType::U8,
    },
    FieldDesc {
        name: "TradSesStatus",
        offset: 14,
        ty: FieldType::U8,
    },
    FieldDesc {
        name: "MarketCondition",
        offset: 15,
        ty: FieldType::U8,
    },
    FieldDesc {
        name: "FastMarketIndicator",
        offset: 16,
        ty: FieldType::U8,
    },
    FieldDesc {
        name: "TESTradSesStatus",
        offset: 17,
        ty: FieldType::U8,
    },
    FieldDesc {
        name: "Pad6",
        offset: 18,
        ty: FieldType::FixedBytes(6),
    },
];

pub mod product_summary {
    pub const TEMPLATE_ID: u16 = 13600;
    pub const MIN_BLOCK_LEN: usize = 24;
    pub const BODY_LEN_OFFSET: usize = 0;
    pub const TEMPLATE_ID_OFFSET: usize = 2;
    pub const MSG_SEQ_NUM_OFFSET: usize = 4;
    pub const LAST_MSG_SEQ_NUM_PROCESSED_OFFSET: usize = 8;
    pub const TRADING_SESSION_ID_OFFSET: usize = 12;
    pub const TRADING_SESSION_SUB_ID_OFFSET: usize = 13;
    pub const TRAD_SES_STATUS_OFFSET: usize = 14;
    pub const MARKET_CONDITION_OFFSET: usize = 15;
    pub const FAST_MARKET_INDICATOR_OFFSET: usize = 16;
    pub const TESTRAD_SES_STATUS_OFFSET: usize = 17;
    pub const PAD6_OFFSET: usize = 18;
}

pub const INSTRUMENTSUMMARY_FIELDS: &[FieldDesc] = &[
    FieldDesc {
        name: "BodyLen",
        offset: 0,
        ty: FieldType::U16Le,
    },
    FieldDesc {
        name: "TemplateID",
        offset: 2,
        ty: FieldType::U16Le,
    },
    FieldDesc {
        name: "MsgSeqNum",
        offset: 4,
        ty: FieldType::U32Le,
    },
    FieldDesc {
        name: "SecurityID",
        offset: 8,
        ty: FieldType::I64Le,
    },
    FieldDesc {
        name: "LastUpdateTime",
        offset: 16,
        ty: FieldType::U64Le,
    },
    FieldDesc {
        name: "TrdRegTSExecutionTime",
        offset: 24,
        ty: FieldType::U64Le,
    },
    FieldDesc {
        name: "TotNoOrders",
        offset: 32,
        ty: FieldType::U16Le,
    },
    FieldDesc {
        name: "SecurityStatus",
        offset: 34,
        ty: FieldType::U8,
    },
    FieldDesc {
        name: "SecurityTradingStatus",
        offset: 35,
        ty: FieldType::U8,
    },
    FieldDesc {
        name: "MarketCondition",
        offset: 36,
        ty: FieldType::U8,
    },
    FieldDesc {
        name: "FastMarketIndicator",
        offset: 37,
        ty: FieldType::U8,
    },
    FieldDesc {
        name: "SecurityTradingEvent",
        offset: 38,
        ty: FieldType::U8,
    },
    FieldDesc {
        name: "SoldOutIndicator",
        offset: 39,
        ty: FieldType::U8,
    },
    FieldDesc {
        name: "HighPx",
        offset: 40,
        ty: FieldType::Decimal64Le,
    },
    FieldDesc {
        name: "LowPx",
        offset: 48,
        ty: FieldType::Decimal64Le,
    },
    FieldDesc {
        name: "ProductComplex",
        offset: 56,
        ty: FieldType::U8,
    },
    FieldDesc {
        name: "NoMDEntries",
        offset: 57,
        ty: FieldType::U8,
    },
    FieldDesc {
        name: "TESSecurityStatus",
        offset: 58,
        ty: FieldType::U8,
    },
    FieldDesc {
        name: "Pad5",
        offset: 59,
        ty: FieldType::FixedBytes(5),
    },
];

pub mod instrument_summary {
    pub const TEMPLATE_ID: u16 = 13601;
    pub const MIN_BLOCK_LEN: usize = 64;
    pub const BODY_LEN_OFFSET: usize = 0;
    pub const TEMPLATE_ID_OFFSET: usize = 2;
    pub const MSG_SEQ_NUM_OFFSET: usize = 4;
    pub const SECURITY_ID_OFFSET: usize = 8;
    pub const LAST_UPDATE_TIME_OFFSET: usize = 16;
    pub const TRD_REG_TSEXECUTION_TIME_OFFSET: usize = 24;
    pub const TOT_NO_ORDERS_OFFSET: usize = 32;
    pub const SECURITY_STATUS_OFFSET: usize = 34;
    pub const SECURITY_TRADING_STATUS_OFFSET: usize = 35;
    pub const MARKET_CONDITION_OFFSET: usize = 36;
    pub const FAST_MARKET_INDICATOR_OFFSET: usize = 37;
    pub const SECURITY_TRADING_EVENT_OFFSET: usize = 38;
    pub const SOLD_OUT_INDICATOR_OFFSET: usize = 39;
    pub const HIGH_PX_OFFSET: usize = 40;
    pub const LOW_PX_OFFSET: usize = 48;
    pub const PRODUCT_COMPLEX_OFFSET: usize = 56;
    pub const NO_MDENTRIES_OFFSET: usize = 57;
    pub const TESSECURITY_STATUS_OFFSET: usize = 58;
    pub const PAD5_OFFSET: usize = 59;
}

pub const SNAPSHOTORDER_FIELDS: &[FieldDesc] = &[
    FieldDesc {
        name: "BodyLen",
        offset: 0,
        ty: FieldType::U16Le,
    },
    FieldDesc {
        name: "TemplateID",
        offset: 2,
        ty: FieldType::U16Le,
    },
    FieldDesc {
        name: "MsgSeqNum",
        offset: 4,
        ty: FieldType::U32Le,
    },
    FieldDesc {
        name: "TrdRegTSTimePriority",
        offset: 8,
        ty: FieldType::U64Le,
    },
    FieldDesc {
        name: "DisplayQty",
        offset: 16,
        ty: FieldType::Decimal64Le,
    },
    FieldDesc {
        name: "Side",
        offset: 24,
        ty: FieldType::U8,
    },
    FieldDesc {
        name: "OrdType",
        offset: 25,
        ty: FieldType::U8,
    },
    FieldDesc {
        name: "HHIIndicator",
        offset: 26,
        ty: FieldType::I8,
    },
    FieldDesc {
        name: "Pad5",
        offset: 27,
        ty: FieldType::FixedBytes(5),
    },
    FieldDesc {
        name: "Price",
        offset: 32,
        ty: FieldType::Decimal64Le,
    },
];

pub mod snapshot_order {
    pub const TEMPLATE_ID: u16 = 13602;
    pub const MIN_BLOCK_LEN: usize = 40;
    pub const BODY_LEN_OFFSET: usize = 0;
    pub const TEMPLATE_ID_OFFSET: usize = 2;
    pub const MSG_SEQ_NUM_OFFSET: usize = 4;
    pub const TRD_REG_TSTIME_PRIORITY_OFFSET: usize = 8;
    pub const DISPLAY_QTY_OFFSET: usize = 16;
    pub const SIDE_OFFSET: usize = 24;
    pub const ORD_TYPE_OFFSET: usize = 25;
    pub const HHIINDICATOR_OFFSET: usize = 26;
    pub const PAD5_OFFSET: usize = 27;
    pub const PRICE_OFFSET: usize = 32;
}

pub const EOBI_MESSAGES: &[MessageDesc] = &[
    MessageDesc {
        template_id: 13001,
        name: "Heartbeat",
        min_block_len: 16,
        event_template: EventTemplate::Heartbeat,
        fields: HEARTBEAT_FIELDS,
    },
    MessageDesc {
        template_id: 13002,
        name: "PacketHeader",
        min_block_len: 32,
        event_template: EventTemplate::PacketHeader,
        fields: PACKETHEADER_FIELDS,
    },
    MessageDesc {
        template_id: 13100,
        name: "OrderAdd",
        min_block_len: 56,
        event_template: EventTemplate::OrderAdd,
        fields: ORDERADD_FIELDS,
    },
    MessageDesc {
        template_id: 13101,
        name: "OrderModify",
        min_block_len: 88,
        event_template: EventTemplate::OrderModify,
        fields: ORDERMODIFY_FIELDS,
    },
    MessageDesc {
        template_id: 13102,
        name: "OrderDelete",
        min_block_len: 64,
        event_template: EventTemplate::OrderDelete,
        fields: ORDERDELETE_FIELDS,
    },
    MessageDesc {
        template_id: 13103,
        name: "OrderMassDelete",
        min_block_len: 24,
        event_template: EventTemplate::OrderMassDelete,
        fields: ORDERMASSDELETE_FIELDS,
    },
    MessageDesc {
        template_id: 13104,
        name: "FullOrderExecution",
        min_block_len: 56,
        event_template: EventTemplate::FullOrderExecution,
        fields: FULLORDEREXECUTION_FIELDS,
    },
    MessageDesc {
        template_id: 13105,
        name: "PartialOrderExecution",
        min_block_len: 56,
        event_template: EventTemplate::PartialOrderExecution,
        fields: PARTIALORDEREXECUTION_FIELDS,
    },
    MessageDesc {
        template_id: 13106,
        name: "OrderModifySamePrio",
        min_block_len: 72,
        event_template: EventTemplate::OrderModifySamePrio,
        fields: ORDERMODIFYSAMEPRIO_FIELDS,
    },
    MessageDesc {
        template_id: 13200,
        name: "TradeReversal",
        min_block_len: 56,
        event_template: EventTemplate::Unsupported,
        fields: TRADEREVERSAL_FIELDS,
    },
    MessageDesc {
        template_id: 13201,
        name: "TradeReport",
        min_block_len: 56,
        event_template: EventTemplate::Unsupported,
        fields: TRADEREPORT_FIELDS,
    },
    MessageDesc {
        template_id: 13202,
        name: "ExecutionSummary",
        min_block_len: 104,
        event_template: EventTemplate::Unsupported,
        fields: EXECUTIONSUMMARY_FIELDS,
    },
    MessageDesc {
        template_id: 13203,
        name: "TESTradeReport",
        min_block_len: 80,
        event_template: EventTemplate::Unsupported,
        fields: TESTRADEREPORT_FIELDS,
    },
    MessageDesc {
        template_id: 13300,
        name: "ProductStateChange",
        min_block_len: 24,
        event_template: EventTemplate::ProductStateChange,
        fields: PRODUCTSTATECHANGE_FIELDS,
    },
    MessageDesc {
        template_id: 13301,
        name: "InstrumentStateChange",
        min_block_len: 56,
        event_template: EventTemplate::InstrumentStateChange,
        fields: INSTRUMENTSTATECHANGE_FIELDS,
    },
    MessageDesc {
        template_id: 13302,
        name: "MassInstrumentStateChange",
        min_block_len: 32,
        event_template: EventTemplate::Unsupported,
        fields: MASSINSTRUMENTSTATECHANGE_FIELDS,
    },
    MessageDesc {
        template_id: 13400,
        name: "AddComplexInstrument",
        min_block_len: 80,
        event_template: EventTemplate::Unsupported,
        fields: ADDCOMPLEXINSTRUMENT_FIELDS,
    },
    MessageDesc {
        template_id: 13401,
        name: "AddFlexibleInstrument",
        min_block_len: 96,
        event_template: EventTemplate::Unsupported,
        fields: ADDFLEXIBLEINSTRUMENT_FIELDS,
    },
    MessageDesc {
        template_id: 13402,
        name: "AddScaledSimpleInstrument",
        min_block_len: 80,
        event_template: EventTemplate::Unsupported,
        fields: ADDSCALEDSIMPLEINSTRUMENT_FIELDS,
    },
    MessageDesc {
        template_id: 13500,
        name: "AuctionBBO",
        min_block_len: 64,
        event_template: EventTemplate::Unsupported,
        fields: AUCTIONBBO_FIELDS,
    },
    MessageDesc {
        template_id: 13501,
        name: "AuctionClearingPrice",
        min_block_len: 56,
        event_template: EventTemplate::Unsupported,
        fields: AUCTIONCLEARINGPRICE_FIELDS,
    },
    MessageDesc {
        template_id: 13502,
        name: "CrossRequest",
        min_block_len: 48,
        event_template: EventTemplate::Unsupported,
        fields: CROSSREQUEST_FIELDS,
    },
    MessageDesc {
        template_id: 13503,
        name: "QuoteRequest",
        min_block_len: 40,
        event_template: EventTemplate::Unsupported,
        fields: QUOTEREQUEST_FIELDS,
    },
    MessageDesc {
        template_id: 13504,
        name: "TopOfBook",
        min_block_len: 64,
        event_template: EventTemplate::Unsupported,
        fields: TOPOFBOOK_FIELDS,
    },
    MessageDesc {
        template_id: 13600,
        name: "ProductSummary",
        min_block_len: 24,
        event_template: EventTemplate::ProductSummary,
        fields: PRODUCTSUMMARY_FIELDS,
    },
    MessageDesc {
        template_id: 13601,
        name: "InstrumentSummary",
        min_block_len: 64,
        event_template: EventTemplate::InstrumentSummary,
        fields: INSTRUMENTSUMMARY_FIELDS,
    },
    MessageDesc {
        template_id: 13602,
        name: "SnapshotOrder",
        min_block_len: 40,
        event_template: EventTemplate::SnapshotOrder,
        fields: SNAPSHOTORDER_FIELDS,
    },
];

#[inline]
pub fn eobi_message(template_id: u16) -> Option<&'static MessageDesc> {
    EOBI_MESSAGES
        .iter()
        .find(|desc| desc.template_id == template_id)
}

pub fn validate_eobi_schema() -> Result<(), String> {
    for desc in EOBI_MESSAGES {
        desc.validate()
            .map_err(|field| format!("{} field {} exceeds min block len", desc.name, field))?;
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn eobi_descriptors_are_in_bounds() {
        validate_eobi_schema().unwrap();
    }

    #[test]
    fn eobi_lookup_finds_generated_templates() {
        assert_eq!(
            eobi_message(13002).unwrap().event_template,
            EventTemplate::PacketHeader
        );
        assert_eq!(
            eobi_message(13100).unwrap().event_template,
            EventTemplate::OrderAdd
        );
        assert_eq!(
            eobi_message(13101).unwrap().event_template,
            EventTemplate::OrderModify
        );
        assert_eq!(
            eobi_message(13106).unwrap().event_template,
            EventTemplate::OrderModifySamePrio
        );
        assert_eq!(
            eobi_message(13102).unwrap().event_template,
            EventTemplate::OrderDelete
        );
        assert_eq!(
            eobi_message(13103).unwrap().event_template,
            EventTemplate::OrderMassDelete
        );
        assert_eq!(
            eobi_message(13105).unwrap().event_template,
            EventTemplate::PartialOrderExecution
        );
        assert_eq!(
            eobi_message(13104).unwrap().event_template,
            EventTemplate::FullOrderExecution
        );
        assert_eq!(
            eobi_message(13300).unwrap().event_template,
            EventTemplate::ProductStateChange
        );
        assert_eq!(
            eobi_message(13301).unwrap().event_template,
            EventTemplate::InstrumentStateChange
        );
        assert_eq!(
            eobi_message(13601).unwrap().event_template,
            EventTemplate::InstrumentSummary
        );
        assert_eq!(
            eobi_message(13602).unwrap().event_template,
            EventTemplate::SnapshotOrder
        );
        assert!(eobi_message(9999).is_none());
    }
}
